Photocopy/Controllers/Cms/AuthController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Photocopy.Entities.Domain;
using System.Security.Claims;
using Photocopy.Core.AppContext;
using Photocopy.Entities.Dto;
using Photocopy.Entities;
using Photocopy.Core.Interface.Services;

namespace Photocopy.CMS.Controllers
{
    [Route("cms")]
    public class AuthController : Controller
    {
        private readonly ILogger<AuthController> _logger;
        private readonly IUserService _userService;

        public AuthController(ILogger<AuthController> logger, IUserService userService)
        {
            _logger = logger;
            _userService = userService;
        }
        [Route("panel")]
        public IActionResult Index(ErrorResult res)
        {
            return View("/Views/_CMS/Auth/Index.cshtml",res);
        }

        [HttpPost]
        [Route("Login")]
        public IActionResult Login(string username, string password)
        {

            UserDto user = _userService.GetUserByUsername(username,password);

            if (user == null)            
                return RedirectToAction("panel", "cms",new ErrorResult { Message = "Kullanıcı Bilgileri Hatalıdır." });
            
            var result = user.Password == password;
            ClaimsIdentity identity = null;
            bool isAuthenticate = false;
            if (result)
            {
                identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                foreach (var item in user.UserRoles)
                {
                    identity.AddClaim(new Claim(ClaimTypes.Role, item.Name));
                }
                identity.AddClaim(new Claim(ClaimTypes.Name, username));
                isAuthenticate = true;
            }
            if (isAuthenticate)
            {
                var principal = new ClaimsPrincipal(identity);
                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                return RedirectToAction("anasayfa","cms");
            }
            return RedirectToAction("panel", "cms", new ErrorResult { Message = "Kullanıcı Bilgileri Hatalıdır." });

        }
        [Route("cikis")]
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("panel", "cms");
        }
    }
}

Photocopy/Controllers/Cms/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using Photocopy.Entities.Domain.FixType;
using Photocopy.Entities.Domain;
using Photocopy.Entities.Dto;
using AutoMapper;
using Photocopy.Core.AppContext;
using Photocopy.Core.Interface.Services;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Xml.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Photocopy.CMS.Controllers
{
    [Route("cms")]
    public class BlogController : Controller
    {
        private readonly ILogger<BlogController> _logger;
        private IBlogNodeService _service;
        private readonly IMapper _mapper;

        public BlogController(ILogger<BlogController> logger, IBlogNodeService service, IMapper mapper)
        {
            _logger = logger;
            _service = service;
            _mapper = mapper;
        }


        #region Blog Node
        [HttpGet]
        [Route("blog-listesi")]
        public IActionResult BlogNodeList()
        {
            var model = _service.GetBlogNodeAll();

            return View("/Views/_CMS/Blog/BlogNodeList.cshtml", model);


        }

        [HttpGet]
        [Route("blog-detay")]
        public IActionResult BlogNode(int blogId)
        {

            BlogNodeDto outModel = _service.GetBlogNodeDetail(blogId);

            return View("/Views/_CMS/Blog/BlogNode.cshtml", outModel);
        }	
		[HttpPost]
        [Route("blog-detay")]
        public async Task<IActionResult> BlogNodeAsync(int Id, string Name)
        {
            BlogNodeDto node =await  _service.SaveOrUpdateBlogNodeAsync(new BlogNodeDto { Id = Id, Name = Name, ContentPageType = ContentPageType.Blog });
            return RedirectToAction("blog-detay","cms", new { blogId = node.Id });
        }

		[HttpPost]
        [Route("DeleteBlogNode")]
        public async Task<IActionResult> DeleteBlogNodeAsync(int blogId)
        {
            await _service.DeleteBlogNode(blogId);
            return RedirectToAction("blog-listesi", "cms");
        }
		#endregion

		#region Blog Page

		[HttpGet]
        [Route("blog-sayfasi")]
        public IActionResult BlogPage(int blogId, int? blogPageId)
        {

            BlogPageDto outModel = new BlogPageDto { Id = blogPageId, ContentNodeId = blogId };
            if (blogPageId != null) outModel = _service.GetBlogPageDetail(blogPageId.Value);
            return View("/Views/_CMS/Blog/BlogPage.cshtml", outModel);
        }
        [HttpPost]
        [Route("blog-sayfasi")]
        public async Task<IActionResult> BlogPageAsync(BlogPageDto page, IFormFile MainImagePath, IFormFile ThumbImagePath)
        {

            page.MainImagePath = Base64ToImage(MainImagePath);
            page.ThumbImagePath = Base64ToImage(ThumbImagePath);
            BlogPageDto pageModel = await _service.SaveOrUpdateBlogPageAsync(page);

            return RedirectToAction("blog-sayfasi","cms", new { blogId = pageModel.ContentNodeId, blogPageId = pageModel.Id });


        }
		[HttpPost]
        [Route("DeleteBlogPage")]
        public async Task<IActionResult> DeleteBlogPageAsync(int blogPageId, int blogId)
        {
            await _service.DeleteBlogPage(blogPageId);
            return RedirectToAction("blog-detay","cms", new { blogId = blogId });

        }
        #endregion

        private string Base64ToImage(IFormFile file)
        {
            string str = "";

            if (file != null)
            {
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    str = Convert.ToBase64String(fileBytes);
                    // act on the Base64 data
                }
            }


            return str;
        }

    }
}

Photocopy/Controllers/Cms/CmsController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Photocopy.Entities.Domain;
using System.Diagnostics;
using System.Security.Claims;
using Photocopy.Core.AppContext;
using Microsoft.AspNetCore.Authorization;

namespace Photocopy.CMS.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Route("cms/anasayfa")]
        public IActionResult Index()
        {
            return View("/Views/_CMS/Home/Index.cshtml");
        }
    }
}

Photocopy/Controllers/Cms/CutomerController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Photocopy.Core.AppContext;
using Photocopy.Core.Interface.Services;
using Photocopy.Entities.Domain;
using Photocopy.Entities.Dto;
using Photocopy.Service.Services;

namespace Photocopy.CMS.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ILogger<CustomerController> _logger;
        private ICustomerService _service;

        private readonly IMapper _mapper;

        public CustomerController(ILogger<CustomerController> logger, ICustomerService service, IMapper mapper)
        {
            _logger = logger;
            _service = service;
            _mapper = mapper;
        }

        [Route("cms/musteri-detay")]
        [HttpGet]
        public IActionResult Index(int customerId)
        {
            CustomerDto customer = _service.GetCustomerById(customerId);

            return View("/Views/_CMS/Customer/Index.cshtml", customer);

        }
        [Route("cms/musteri-listesi")]
        public IActionResult CustomerList()
        {
            IList<CustomerListDto> customers = _service.GetCustomerList();
            return View("/Views/_CMS/Customer/CustomerList.cshtml", customers);

        }

        [Route("cms/musteri-detay")]
        [HttpPost]
        public async Task<IActionResult> Index(CustomerDto customer)
        {
            CustomerDto customerDto = await _service.SaveOrUpdate(customer);

            return RedirectToAction("musteri-detay","cms", new { customerId = customer.Id });

        }
        [Route("cms/DeleteCustomer")]
        public async Task<IActionResult> DeleteCustomerAsync(int customerId)
        {
            await _service.DeleteCustomer(customerId);
            return RedirectToAction("musteri-listesi", "cms");

        }
        [Route("cms/DeleteCustomerAddress")]
        public async Task<IActionResult> DeleteCustomerAddressAsync(int addressId,int customerId)
        {
            await _service.DeleteCustomerAddress(addressId);
            return RedirectToAction("musteri-detay","cms", new { customerId = customerId });

        }
    }
}

Photocopy/Controllers/Cms/FaqController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Photocopy.Core.AppContext;
using Photocopy.Core.Interface.Services;
using Photocopy.Entities;
using Photocopy.Entities.Domain;
using Photocopy.Entities.Dto;
using System.Xml.Linq;

namespace Photocopy.CMS.Controllers
{
    public class FaqController : Controller
    {
        private readonly ILogger<FaqController> _logger;
        private IFaqService _service;
        private readonly IMapper _mapper;

        public FaqController(ILogger<FaqController> logger, ApplicationContext db, IMapper mapper, IFaqService service)
        {
            _logger = logger;
           _service= service;
            _mapper = mapper;
        }
        [Route("cms/sikca-sorulan-sorular-detay")]
        public IActionResult Faq(int faqId)
        {
            FaqDto faq = _service.GetFaqById(faqId) ??  new FaqDto();

            return View("/Views/_CMS/Faq/Faq.cshtml", faq);

        }
        [Route("cms/sikca-sorulan-sorular")]
        public IActionResult FaqList()
        {
            IList<FaqDto> faqs = _service.GetFaqList();
            return View("/Views/_CMS/Faq/FaqList.cshtml", faqs);

        }
        [Route("cms/SaveOrUpdateFaq")]        
        public async Task<IActionResult> SaveOrUpdateFaqAsync(FaqDto faq)
        {

            FaqDto model=await _service.SaveOrUpdateAsync(faq);

            return RedirectToAction("sikca-sorulan-sorular-detay", "cms", new { faqId = model.Id } );

        }
        [Route("cms/DeleteFaq")]
        public async Task<IActionResult> DeleteFaqAsync(int faqId)
        {
           await _service.DeleteFaq(faqId);
            return RedirectToAction("sikca-sorulan-sorular","cms");

        }
    }
}

Photocopy/Controllers/Cms/OrderManagementController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Photocopy.Core.Interface.Services;
using Photocopy.Entities.Dto;

namespace Photocopy.CMS.Controllers
{
    public class OrderManagementController : Controller
    {
        private readonly ILogger<OrderManagementController> _logger;
        private IOrderService _service;
        private readonly IMapper _mapper;

        public OrderManagementController(ILogger<OrderManagementController> logger, IOrderService service, IMapper mapper)
        {
            _logger = logger;
            _service = service;
            _mapper = mapper;
        }
        [HttpGet]
        [Route("cms/siparis-detay")]
        public IActionResult Index(int orderId)
        {
            return View("/Views/_CMS/OrderManagement/Index.cshtml", _service.GetOrderDetail(orderId));
        }
        [HttpPost]
        [Route("cms/siparis-detay")]
        public IActionResult Index(OrderListDto order)
        {
            _service.SetOrderDetail(order);
            return RedirectToAction("siparis-detay", "cms", new  { orderId=order.Id });
        }
        [Route("cms/siparis-yonetimi")]
        public IActionResult OrderManagementList()
        {
            return View("/Views/_CMS/OrderManagement/OrderManagementList.cshtml", _service.GetOrders());
        }
        [Route("cms/UploadData")]
        public async Task<IActionResult> UploadData(Guid uploadDataId)
        {
            UploadDataDto data = _service.GetUploadData(uploadDataId);
            var bytes = Convert.FromBase64String(data.FilePath);
            return File(bytes, "application/pdf", data.FileName);
        }
        [Route("cms/fiyat-listesi")]
        public IActionResult PriceList()
        {
           IList<LookupPriceListDto> list= _service.GetAllLookupPrice();
            return View("/Views/_CMS/OrderManagement/LookupPrice.cshtml", list);

        }

        [HttpPost]
        [Route("cms/SetLookupPrice")]
        public IActionResult SetLookupPrice(SetLookupPriceCmsDto lookupPriceCmsDto)
        {
            _service.SetLookupPrice(lookupPriceCmsDto);
            return RedirectToAction("fiyat-listesi","cms", "OrderManagement");
        }

    }
}

Photocopy/Controllers/Cms/SliderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Photocopy.Core.AppContext;
using Photocopy.Core.Interface.Services;
using Photocopy.Entities;
using Photocopy.Entities.Domain;
using Photocopy.Entities.Domain.FixType;
using Photocopy.Entities.Dto;
using System.Xml.Linq;

namespace Photocopy.CMS.Controllers
{
    public class SliderController : Controller
    {
        private readonly ILogger<SliderController> _logger;
        private ISliderService _service;
        private readonly IMapper _mapper;

        public SliderController(ILogger<SliderController> logger, ISliderService service, IMapper mapper)
        {
            _logger = logger;
            _service = service;
            _mapper = mapper;
        }
        [HttpGet]
        [Route("cms/slider")]
        public IActionResult Slider(int sliderId)
        {
            SliderDto slider = _service.GetSliderById(sliderId) ?? new SliderDto(); ;
            return View("/Views/_CMS/Slider/Slider.cshtml", slider);

        }
        [HttpGet]
        [Route("cms/slider-listesi")]
        public IActionResult SliderList()
        {
            IList<SliderDto> sliders = _service.GetSliderList();
            return View("/Views/_CMS/Slider/SliderList.cshtml", sliders);

        }
        [HttpPost]
        [Route("cms/slider")]
        public async Task<IActionResult> SliderAsync(SliderDto slider, IFormFile ImagePath, IFormFile MobileImagePath)
        {
            slider.ImagePath = Base64ToImage(ImagePath);
            slider.MobileImagePath = Base64ToImage(MobileImagePath);
            slider =await _service.SaveOrUpdateAsync(slider);

            return RedirectToAction("slider","cms", new { sliderId = slider.Id });

        }
        [Route("cms/DeleteSlider")]
        public async Task<IActionResult> DeleteSliderAsync(int sliderId)
        {
            await _service.DeleteSlider(sliderId);
            return RedirectToAction("slider-listesi", "cms" );

        }

        private string Base64ToImage(IFormFile file)
        {
            string str = "";

            if (file != null)
            {
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    var fileBytes = ms.ToArray();
                    str = Convert.ToBase64String(fileBytes);
                    // act on the Base64 data
                }
            }


            return str;
        }

    }
}

Photocopy/ViewComponent/OrderStateViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Photocopy.Core.Interface.Services;
using Photocopy.Entities.Dto;

namespace Photocopy.CMS.Component
{
    public class OrderStateViewComponent : ViewComponent
    {
		private IOrderService _service;

		public OrderStateViewComponent(IOrderService service)
		{
			_service = service;
		}

		public async Task<IViewComponentResult> InvokeAsync(int Id)
        {
			OrderStateDto orderStates = new OrderStateDto { Items = _service.GetAllOrderState(), Value = Id } ;
            return View(orderStates);
        }
    }
}

Photocopy/Views/_CMS/OrderManagement/Index.cshtml
@model Photocopy.Entities.Dto.OrderListDto

@{
    ViewData["Title"] = "Sipariş Detay";
    Layout = "_LayoutCms";
}
<div class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title">Sipariş Detay</h4>
                    </div>
                    <div class="card-body">
                        <form autocomplete="off" method="post" action="/cms/siparis-detay">
                            <input type="hidden" name="Id" value="@Model.Id" />
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Müşteri Numarası</label>
                                        <a href="/cms/musteri-detay?customerId=@Model.CustomerId" class=" btn btn-warning btn-link btn-sm">@Model.CustomerId</a>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Kargo Firması</label>
                                        <select class="form-select custom-select" aria-label="Default select example" name="CargoCompany" value="@Model.CargoCompanyId" disabled>
                                            <option value="0">Mng Kargo</option>
                                            <option value="1">Aras Kargo</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Ödeme Türü</label>
                                        <select class="form-select custom-select" aria-label="Default select example" name="PaymentType" value="@Model.PaymentType" disabled>
                                            <option value="0">Kredi Kartı</option>
                                            <option value="1">Havale</option>
                                        </select>
                                    </div>
                                </div>
                              
                              
                            </div>
                            <div class="row">

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Sipariş Notu</label>
                                        <input type="text" class="form-control" name="Notes" value="@Model.Notes" disabled>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Toplam Fiyat</label>
                                        <input type="email" class="form-control" value="@Model.TotalPrice" name="TotalPrice" disabled>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Ödeme Durumu</label>
                                        <select class="form-select custom-select" aria-label="Default select example" name="PaymentState">
                                            <option value="0"  >Ödeme İşlemi Tamamlanmadı</option>
                                            <option value="1">Ödeme İşlemi Tamamlanacak</option>                                            
                                            <option value="2">Ödeme İşlemi Tamamlandı</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-3">

                                    @await Component.InvokeAsync("OrderState",Model.OrderStateId)

                                </div>
                            </div>
                            <button type="submit" class="btn btn-info pull-right">@(Model.Id != null ? "Güncelle" : "Ekle")</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-special">
                        <form method="post">
                            <span class="card-title ">@Model.Id Numaralı Sipariş Detay</span>

                        </form>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-info">
                                <th>
                                    Sipariş Detay No
                                </th>
                                <th>
                                    Format
                                </th>
                                <th>
                                    Kombinasyon
                                </th>
                                <th>
                                    Taraf
                                </th>
                                <th>
                                    Yön
                                </th>
                                <th>
                                    Renk
                                </th>
                                <th>
                                    Kalite
                                </th>
                                <th>
                                    Ciltleme
                                </th>
                                <th>
                                    Kağıt Türü
                                </th>
                                <th>
                                    Pdf Sayfa Sayısı
                                </th>
                                <th>
                                    Dosya Sayısı
                                </th>
                                <th>
                                    Birim Fiyat (TL)
                                </th>
                                <th>
                                    Sayfa Fiyat (TL)
                                </th>
                                <th>
                                    Dosya Fiyat (TL)
                                </th>

                                <th class="td-actions text-right">
                                    Dosya
                                </th>

                                </thead>
                                <tbody>
                                    @foreach (var item in Model.OrderDetails)
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.Format.ToString()</td>
                                            <td>@item.Combination.ToString()</td>
                                            <td>@item.Side.ToString()</td>
                                            <td>@item.Rotate.ToString()</td>
                                            <td>@(item.Colourfull == 1 ? "Renkli" : "Siyah Beyaz")</td>
                                            <td>@(item.Quality == 1 ? "Yüksek" : "Standart")</td>
                                            <td>@item.Binding</td>
                                            <td>@item.PaperType</td>
                                            <td>@item.PdfPageCount</td>
                                            <td>@item.Count</td>
                                            <td>@item.UnitPrice</td>
                                            <td>@item.PagePrice</td>
                                            <td>@item.FilePrice</td>

                                            <td><a href="/cms/UploadData?uploadDataId=@item.UploadDataId" class=" btn btn-warning btn-link btn-sm">Dosyayı Görüntüle</a></td>

                                        </tr>
                                    }

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Photocopy/Views/_CMS/OrderManagement/LookupPrice.cshtml
@model IList<Photocopy.Entities.Dto.LookupPriceListDto>
@{
    ViewData["Title"] = "Fiyat Güncelle";
    Layout = "_LayoutCms";
}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-special">
                        <span class="card-title ">Fiyat Listesi</span>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-info">
                                <th>
                                    ID
                                </th>
                                <th>
                                    Tür
                                </th>
                                <th>
                                    Açıklama
                                </th>
                                <th>
                                    Fiyat
                                </th>
                                <th>
                                    Renk
                                </th>
                                <th>
                                    Kalite
                                </th>
                                <th class="td-actions text-right">
                                    Güncelle
                                </th>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr class="row-@item.Id">
                                            <td>@item.Id</td>
                                            <td>@item.Tag</td>
                                            <td>@item.Text</td>
                                            <td><input type="text" value="@item.DefaultValue" class="value" /> TL</td>
                                            <td>@(item.IsColourful == 0 ? "Siyah Beyaz" : "Renkli")</td>
                                            <td>@(item.IsQuality == 0 ? "Standart" : "Kaliteli")</td>
                                            <td class="td-actions text-right">
                                                <form>
                                                    <button type="button" rel="tooltip" data-id="@item.Id" title="Fiyat Güncelle" class="btn btn-info btn-link btn-sm btn-update">
                                                        <i class="material-icons">edit</i>
                                                    </button>
                                                </form>

                                            </td>
                                        </tr>
                                    }

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
    {
    <script>
        $('form .btn-update').click(function (e) {
            e.preventDefault();
            var id = $(this).attr("data-id");
            var value = $(".row-" + id + " input.value").val();
            $.ajax({
                type: "Post",
                url: "/cms/SetLookupPrice",
                data: { id: id, defaultValue: value },
                success: function (data) {
                    $.toast({
                        type:"success",
                        autoDismiss: true,
                        message: 'Fiyat Güncelleme Başarılı.'
                    });
                }
                , error: function (data) {
                    $.toast({
                        type:"error",
                        autoDismiss: true,
                        message: 'Fiyat Güncelleme Başarısız.'
                    });
                }
            });
        });
    </script>
}