Photocopy.CMS/Controllers/FaqController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Photocopy.Core.AppContext;
using Photocopy.Core.Interface.Services;
using Photocopy.Entities;
using Photocopy.Entities.Domain;
using Photocopy.Entities.Dto;

namespace Photocopy.CMS.Controllers
{
    public class FaqController : Controller
    {
        private readonly ILogger<FaqController> _logger;
        private IFaqService _service;
        private readonly IMapper _mapper;

        public FaqController(ILogger<FaqController> logger, ApplicationContext db, IMapper mapper, IFaqService service)
        {
            _logger = logger;
           _service= service;
            _mapper = mapper;
        }

        public IActionResult Faq(int faqId)
        {
            FaqDto faq = _service.GetFaqById(faqId) ??  new FaqDto();

            return View(faq);

        }
        public IActionResult FaqList()
        {
            IList<FaqDto> faqs = _service.GetFaqList();
            return View(faqs);

        }
        public IActionResult SaveOrUpdateFaq(FaqDto faq)
        {

            _service.SaveOrUpdateAsync(faq);

            return View("/Views/Faq/Faq.cshtml", faq);

        }

        public IActionResult DeleteFaq(int faqId)
        {
            _service.DeleteFaq(faqId);
            return FaqList();

        }
    }
}

Photocopy.CMS/Views/Faq/Faq.cshtml
@model Photocopy.Entities.Dto.FaqDto

@{
    ViewData["Title"] = "Soru Güncelle";
    Layout = "_Layout";
}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-special">
                        <h4 class="card-title ">Soru</h4>
                    </div>
                    <div class="card-body">
                        @using (Html.BeginForm("SaveOrUpdateFaq", "Faq", FormMethod.Post, new { autocomplete = "off" }))
                        {
                            <input type="hidden" name="Id" value="@Model.Id" />
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Soru</label>
                                        <input type="text" name="Question" class="form-control" value="@Model.Question" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Alt Soru</label>
                                        <input type="text" name="SubQuestion" class="form-control" value="@Model.SubQuestion" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="bmd-label-floating">Cevap</label>
                                        <input type="text" name="Answer" class="form-control" value="@Model.Answer" required>
                                    </div>
                                </div>
                            </div>


                            <button type="submit" class="btn btn-info pull-right btn-sm">@(Model.Id != null ? "Güncelle" : "Ekle") </button>
                            <div class="clearfix"></div>
                        }
                    </div>
                </div>
            </div>

        </div>


   

    </div>
</div>

Photocopy.CMS/Views/Faq/FaqList.cshtml
@model IList<Photocopy.Entities.Dto.FaqDto>

@{
    ViewData["Title"] = "Sıkça Sorulan Sorular Listesi";
    Layout = "_Layout";
}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-special">
                        <form method="post" action="/Faq/Faq?faqId=">
                            <span class="card-title ">Soru Listesi</span>

                            <button type="submit" class="btn btn-info pull-right btn-sm">Soru Oluştur</button>
                        </form>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead class=" text-info">
                                <th>
                                    ID
                                </th>
                                <th>
                                   Soru
                                </th>
                                <th class="td-actions text-right">
                                    İşlemler
                                </th>

                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.Question</td>
                                            <td class="td-actions text-right">
                                                <form method="post" action="/Faq/Faq?faqId=@item.Id">
                                                    <button type="submit" rel="tooltip" title="Edit Task" class="btn btn-info btn-link btn-sm">
                                                        <i class="material-icons">edit</i>
                                                    </button>
                                                </form>
                                                <form >
                                                   <button type="button" rel="tooltip" title="Remove" class="btn btn-warning btn-link btn-sm delete" data-faqId="@item.Id">
                                                    <i class="material-icons">delete</i>
                                                </button>
                                                </form>
                                                
                                            </td>
                                        </tr>
                                    }

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal Delete data-bs-toggle="modal" data-bs-target="#deleteModal"-->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="/Faq/DeleteFaq" method="post">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Sil</h5>
                    <input type="hidden" id="faqId" name="faqId" value="" />

                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Silmek İstediğinize Emin misiniz?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Vazgeç</button>
                    <button type="submit" class="btn btn-primary">Sil</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section scripts
    {
    <script>
        $('form .delete').click(function (e) {
            e.preventDefault();

            $("#faqId").val($(this).attr("data-faqId"));


            $('#deleteModal').modal({
                show: true
            });
        });
    </script>
}